# Generated by Django 4.2.3 on 2023-09-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0002_artist_delete_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='artist_id',
        ),
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=20),
        ),
    ]
