# Generated by Django 4.2.3 on 2023-09-17 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicdb', '0003_remove_artist_artist_id_alter_artist_artist_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='artist_name',
            field=models.CharField(max_length=50),
        ),
    ]
